### ISSUE TITLE
Default last subnet 50 should get replaced to 254

### ISSUE THREAD

**Issue by guyluz11** [git-elliot/network_tools#10]
Most of the routers in the world have a range of 254 IPs.

The default in the package in all places is 50.

Not sure if this is all:

https://github.com/git-elliot/network_tools/blob/a8d29652699ac518a126581e469d0a1bb5a5e353/lib/src/host_scanner.dart#L20
 
https://github.com/git-elliot/network_tools/blob/a8d29652699ac518a126581e469d0a1bb5a5e353/lib/src/host_scanner.dart#L100

https://github.com/git-elliot/network_tools/blob/a8d29652699ac518a126581e469d0a1bb5a5e353/example/main.dart#L8

https://github.com/git-elliot/network_tools/blob/a8d29652699ac518a126581e469d0a1bb5a5e353/example/main.dart#L23

**Comment by git-elliot** [comment]
Please verify and close this issue. 
For discover:
https://github.com/git-elliot/network_tools/blob/ccc757c703bc46b6f037a04f5cfd631d02edb5d5/lib/src/host_scanner.dart#L14

For discoverPort:
https://github.com/git-elliot/network_tools/blob/ccc757c703bc46b6f037a04f5cfd631d02edb5d5/lib/src/host_scanner.dart#L77

**Comment by guyluz11** [comment]
I think it is better if you will change in the example too
