### ISSUE TITLE
Example crash on Windows

### ISSUE THREAD

**Issue by guyluz11** [git-elliot/network_tools#14]
Not working on Windows

``` dart
Unhandled exception:
SocketException: Connection failed (OS Error: The requested address is not valid in its context.
, errno = 10049), address = 192.168.1.1, port = 0
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:681:35)
#1      _NativeSocket.connect (dart:io-patch/socket_patch.dart:940:12)
#2      _RawSocket.connect (dart:io-patch/socket_patch.dart:1796:26)
#3      RawSocket.connect (dart:io-patch/socket_patch.dart:21:23)
#4      Socket._connect (dart:io-patch/socket_patch.dart:2019:22)
#5      Socket.connect (dart:io/socket.dart:770:21)
#6      PortScanner.connectToPort (package:network_tools/src/port_scanner.dart:131:37)
#7      PortScanner.customDiscover (package:network_tools/src/port_scanner.dart:75:28)
<asynchronous suspension>

Process finished with exit code 255

```

Tested with my home IP but posted with the example IP.

**Comment by git-elliot** [comment]
Address is hardcoded. Maybe we should take it as a command line argument.

**Comment by guyluz11** [comment]
The problem is not that it is use the wrong address by default, but this is another issue that we should think what is the best way to solve it.

Did you test this package on Windows?.

**Comment by git-elliot** [comment]
It is not tested on windows. I guess startPort when set to 0 getting us into trouble.

**Comment by guyluz11** [comment]
> It is not tested on windows. I guess startPort when set to 0 getting us into trouble.

Correct, after changing start port in the example 

https://github.com/git-elliot/network_tools/blob/f9c811e73833e86af2739a1680fcd3d6ba1e35ab/example/main.dart#L53

to 1 the program run on Windows.
