### ISSUE TITLE
PortScanner.discover does not find some of my ports

### ISSUE THREAD

**Issue by guyluz11** [git-elliot/network_tools#18]
Running 
 ```
PortScanner.discover(
    target,
    startPort: 1,
    endPort: 65535,
    progressCallback: (progress) {},
)
```
And I am missing ports 111, 8080, 8123, 8883 in the results.

**Comment by git-elliot** [comment]
Try increasing timeout.

**Comment by guyluz11** [comment]
It worked thanks.

Should we change the default timeout now that it retrieves results faster?

**Comment by guyluz11** [comment]
Found that some of my missing ports including the famous 8080 got show on `milliseconds: 2000`, and not even in `milliseconds: 1000`.

Will add it to my pull request.
