### ISSUE TITLE
Support multiple platforms

### ISSUE THREAD

**Issue by guyluz11** [git-elliot/network_tools#2]
Currently we are getting 10 less points in [pub.dev](https://pub.dev/packages/network_tools/score) for missing support for multiple platforms

![image](https://user-images.githubusercontent.com/9304740/129699702-bdf6c33f-2937-45e2-a53b-1690bc61fddc.png)

This is caused because `dart:io` is missing support for web and more
for that we can use [universal_io](https://pub.dev/packages/universal_io) that is

> A cross-platform dart:io that works in all platforms (browsers, mobile, desktop, and server-side).

**Comment by git-elliot** [comment]
I appreciate your interest in moving forward to web as well, but there is one bottleneck and that is the dependency `dart_ping` for this library. `dart_ping` currently not supporting JS. I though of implementing something similar as `dart_ping` and support web as well but I guess that's a ton of work for a busy Individual.

**Comment by guyluz11** [comment]
I have opened an issue for adding JS support in dart_pping, feel free to like 
https://github.com/point-source/dart_ping/issues/15

Is there a chance that [socket_io_client](https://pub.dev/packages/socket_io_client/example) can do what you need?.

**Comment by point-source** [comment]
Hey guys, author of dart_ping here. I replied to the issue you opened with an explanation as to why I cannot add web support. 

However, if you simply want your tool to show as supporting web on pub but do not actually need ping functionality on web, you can make use of [conditional imports](https://dart.dev/guides/libraries/create-library-packages#conditionally-importing-and-exporting-library-files) to only import dart_ping when the platform is not web. This should allow users to make use of all web-enabled features of your application and will appropriately show web support on pub.

**Comment by guyluz11** [comment]
Thanks @point-source for your answer, I will close this issue for now.

**Comment by git-elliot** [comment]
@guyluz11 Things are really restricted when it comes to web browser.
