### ISSUE TITLE
Even more points in pub.dev page

### ISSUE THREAD

**Issue by guyluz11** [git-elliot/network_tools#20]
I believe we can reach even more points in [pub.dev page](https://pub.dev/packages/network_tools/score).

Currently it is subtracting points on `pubspec.yaml` 

> Documentation URL isn't helpful.

Not sure what it is but it can be good to fix it and get more points.

![image](https://user-images.githubusercontent.com/9304740/150861761-fb11b46c-670a-4990-bd23-4c9b275b95c7.png)

Maybe we can even support the web/flutter js by converting the dart from dart.io to [universal_io](https://pub.dev/packages/universal_io).
It does not remove any points for us but why not if it is that easy

![image](https://user-images.githubusercontent.com/9304740/150862587-ffcbe392-e640-4fff-bd5e-b06c8db42b2f.png)

**Comment by git-elliot** [comment]
I'll remove documentation url from pubspec.yaml
