### ISSUE TITLE
A possible solution to platform limitation lable

### ISSUE THREAD

**Issue by guyluz11** [git-elliot/network_tools#29]
I think that I have found a new solution to fix platform limitation label issues. 

In the Readme part of https://github.com/point-source/dart_ping ios part it is saying

> [dart_ping_ios](https://github.com/point-source/dart_ping/blob/main/dart_ping_ios) is a plugin which adds cocoa dependencies to support ping on iOS systems. Using this plugin requires the Flutter SDK to be added to your dart project.

This way his package can support both native Linux and flutter-dependent functionality in the same package which is pretty cool.

This could be our current solution to a lot of our problems, this means supporting some functionality only on specific platforms but I think it is better than nothing.

My suggestion is to split the package into dart native and flutter package as dart_ping did (I think), and on some platforms the flutter parts will help us use specific calls that can solve our missing functionality like using native (for example) android (in java) packages or to use flutter only package.

If the developer tries to call some function that supports only a specific platform in the wrong platform it will return empty data or will throw an error that this functionality does not support on that platform.

**Comment by git-elliot** [comment]
As I understood the implementation of `dart_ping_ios`, we could better create a flutter only package called `network_tools_flutter` which will allow us to use flutter packages to support at least certain platforms if not all at the same time.

**Comment by guyluz11** [comment]
@git-elliot  Sounds good
