### ISSUE TITLE
Support for getting host name

### ISSUE THREAD

**Issue by guyluz11** [git-elliot/network_tools#3]
Is there a way to get a hostname/dns name from specific IP?.
Or even better, have a way to get the hostname of all the IPs during the scan?.

If not what are the steps that missing in order to add this feature.

**Comment by git-elliot** [comment]
DNS lookup is already there to get the hostname. As far as search is concerned, it is made on the local wifi network and hence IP addresses would be local also, most probably won't have any name associated with it.

**Comment by guyluz11** [comment]
So I am missing something, where is the hostname stored?, I am expecting it to be stored in the class `ActiveHost` but it does not contain any hostname.

I am creating a [smart hub](https://github.com/CyBear-Jinni/cbj_hub).
I want to recognize smart devices on the network by vendor name which exists in hostname.
Examples: `LIFX-White-5ECF0C`, `ESP_F5B515`

I am thinking of clessefying IP to company by open ports but as `nmap` is showing me this is not always possible
`All 1000 scanned ports on LIFX-White-5ECF0C (55.13.21.149) are closed
`

**Comment by git-elliot** [comment]
Sorry my bad, for confusing the hostname with domain name. It's been pretty while working on this project. Let me check for the hostname. I'll update if I'm able to retrieve it.

**Comment by guyluz11** [comment]
Cool thanks.

On an unrelated note.
I am looking at the code seeing that it cheks one IP at a time, waits for the result and then checks the next IP.
I will try to change it to do it asynchronously, is it something that you will accept as a pull request?.

**Comment by git-elliot** [comment]
I don't know why I kept it synchronised, yeah please try. I'll check the PR and test it. If it does the same thing then I'll merge into the code.

**Comment by git-elliot** [comment]
@guyluz11 Please also tell me about which scanner are you talking about. host_scanner or port_scanner?

**Comment by guyluz11** [comment]
Host scanner.

Also is there a way to remove the `PingSummary` lines?
`PingSummary(transmitted:1, received:0), time: 0 ms, Errors: [NoReply]`

**Comment by git-elliot** [comment]
In host scanner, you can't _yield_ twice that's why for inner stream I used _await for_.

PingSummary lines can be removed by removing this line. i'll not suggest removing it, but adding a flag to the method named debug.

https://github.com/git-elliot/network_tools/blob/dd606bf36f70ff7ba7e4ccff893dd0f493252dd8/lib/src/host_scanner.dart#L51

**Comment by git-elliot** [comment]
I'm unable to find any way to get hostname of local IPs. People are claiming it to be done using `InternetAddress.reverse()` but that only works if the result came from the DNS server.

**Comment by guyluz11** [comment]
Not sure if this helps but [Nmap](https://nmap.org/) tool for Linux is doing that fine and is very popular.
Maybe there is more documentation about the implementation in [Nmap GitHub](https://github.com/nmap/nmap) repo.

I think "Hostname" is also called "local domain name" and "DNS name".

It can be resolved using `avahi-resolve-address` command so I guess we can do it by using `avahi` packages, maybe [avahi](https://pub.dev/packages/avahi) or [multicast_dns](https://pub.dev/packages/multicast_dns).
More research is required.

**Comment by guyluz11** [comment]
I have found a way to do reverse DNS lookup and get the hostname from IP :D.

After getting an InternetAddress object we need to run `.reverse` on it and the `.host` field will get populated.

Example code

```
final InternetAddress internetAddressWithoutHost = InternetAddress('IP');
final InternetAddress internetAddressWithHost = await internetAddressWithoutHost.reverse();
print(internetAddressWithHost.host);
```
I will implement it after my pull requests will get accepted.

**Comment by git-elliot** [comment]
Seems like `internetAddressWithoutHost.reverse()` is added lately.

**Comment by guyluz11** [comment]
Host name functionality got merged into dev branch.

I will close this issue now, thanks.
