### ISSUE TITLE
Can we combine ActiveHost and OpenPort?

### ISSUE THREAD

**Issue by guyluz11** [git-elliot/network_tools#35]
I am thinking that using only one interface will be easier for developers to use our package.

Moreover I think it will be easier to maintain if we will work with one object for hosts.

Can I create pr that will use OpenPort inside ActiveHost and remove the IP from it?.

**Comment by git-elliot** [comment]
So in that sense, ActiveHost will have List<OpenPort> and PortScanner will also return ActiveHost after the scan is completed. Right?

**Comment by guyluz11** [comment]
> So in that sense, ActiveHost will have List and PortScanner will also return ActiveHost after the scan is completed. Right?

Exactly. 
ActiveHost will have List of ports and get returned from PortScanner.

**Comment by git-elliot** [comment]
Yeah we can go ahead with this change.

**Comment by guyluz11** [comment]
Thanks

PR got marged so I am closing this issue
