### ISSUE TITLE
Host scanner can run much faster

### ISSUE THREAD

**Issue by guyluz11** [git-elliot/network_tools#4]
Host scanner can run much faster by getting the host from ping in an async way

https://github.com/git-elliot/network_tools/blob/dd606bf36f70ff7ba7e4ccff893dd0f493252dd8/lib/src/host_scanner.dart#L42

**Comment by guyluz11** [comment]
@git-elliot  can you assign this issue to me?.

**Comment by git-elliot** [comment]
I've assigned. I'll check the code tomorrow and merge after that. Sorry for the delay.

**Comment by guyluz11** [comment]
Thanks, will close this issue now.
