### ISSUE TITLE
Consider `HostScanner.discover` to return a `Future<List<ActiveHost>>` instead of `Stream<ActiveHost>`

### ISSUE THREAD

**Issue by ivirtex** [git-elliot/network_tools#43]
Since all ping actions are started asynchronously, they will complete aprroximately at the same time.
This means that almost all the results are yielded also at the same time, this behaviour doesn't really fit the purpose of Dart's streams.
Converting `HostScanner.discover` to return a `Future` would simplify the code and logic.

**Comment by git-elliot** [comment]
If the address is Class A, user have to wait for all the futures to be completed in order to get the result from getAllPingableDevices(formerly discover) method. 
https://github.com/git-elliot/network_tools/blob/ffcd5ed42a457c0646c5589132f4a6a98ef66667/network_tools/lib/src/host_scanner.dart#L146

**Comment by ivirtex** [comment]
Right, I forgot about the timeout property.
