### ISSUE TITLE
Saving the response time from each device

### ISSUE THREAD

**Issue by guyluz11** [git-elliot/network_tools#9]
We can easily save the response time of each device whenever we get the response.

This could be useful for knowing if there is a problem with the device like overload (it is slowing down) or if it has a weak WiFi signal.

**Comment by git-elliot** [comment]
I guess I should add the whole object of `PingData` in the `ActiveHost` class.

**Comment by git-elliot** [comment]
I have added the `PingData` object to `ActiveHost` class. User can retrieve time using `pingData.response.time`. I hope that fulfil the need of response time.
